
###

GET https://proyecto-tienda-rho.vercel.app/api/productos 

###

POST https://proyecto-tienda-rho.vercel.app/api/productos
Content-Type: application/json

{
  "name": "Celular Xiaomi 15c",
  "price": 430,
  "category": "Electronics",
  "stock": 10,
  "description": "Celular con capacidad de procesamiento alto, 8GB RAM y 512GB ideal para trabajo y juegos.",
  "rating": {
    "rate": 4.7,
    "count": 10
  } 
}

